inherit: 
    - wandb.yaml

model:
    n_dims: 5
    n_positions: 101
    family: gpt2
    n_embd: 64
    n_layer: 1
    n_head: 1

training:
    data: gaussian
    task_kwargs: {}
    batch_size: 128
    learning_rate: 0.0001
    save_every_steps: 10000
    keep_every_steps: 10000
    train_steps: 50001
    curriculum:
        dims:
            start: 5
            end: 5
            inc: 1
            interval: 2000
