inherit: 
    - models/standard.yaml
    - wandb.yaml

model:
    n_dims: 5
    n_positions: 300

training:
    task: linear_regression
    data: gaussian
    task_kwargs: {}
    batch_size: 64
    learning_rate: 0.0001
    save_every_steps: 1000
    keep_every_steps: 100000
    train_steps: 500001
    curriculum:
        dims:
            start: 5
            end: 5
            inc: 1
            interval: 2000
        points:
            start: 30
            end: 30
            inc: 2
            interval: 2000

out_dir: /mnt/scratch/xingyue1/icl/

wandb:
    name: "linear_regression_toy"
